language: cpp
compiler: gcc

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo apt-get install libboost-test-dev

script:
  - bash compile_main.sh
  - bash compile_tests.sh
  - bash run_tests.sh

notifications:
  email:
    - shpakovskij.denis@yandex.ru
